# Generated by Django 6.1 on 2026-08-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(default='Parties', max_length=100),
        ),
    ]
