# Generated by Django 6.1 on 2026-08-29 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_options_remove_event_flyer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='flyer',
            field=models.ImageField(blank=True, help_text='Upload the event flyer/poster.', null=True, upload_to='event_flyers/'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Display this event as the featured event.'),
        ),
    ]
