# Generated by Django 6.1 on 2026-08-29 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_flyer_event_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='description',
            field=models.TextField(blank=True, help_text='Short description displayed to customers.'),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='highlight',
            field=models.BooleanField(default=False, help_text='Mark this ticket as Most Popular.'),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='perks',
            field=models.JSONField(blank=True, default=list, help_text='Enter perks as a JSON list, e.g. ["VIP access", "Free drink"]'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='name',
            field=models.CharField(help_text='Example: Regular, VIP, VVIP', max_length=100),
        ),
    ]
