# Generated by Django 6.1 on 2026-08-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_payment_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email_sent',
            field=models.BooleanField(default=False, help_text='Whether the ticket delivery email has been successfully sent.'),
        ),
    ]
