# Generated by Django 6.1 on 2026-08-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
