# Generated by Django 6.1 on 2026-08-17 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('VALID', 'Active / Eligible for Entry'), ('SCANNED', 'Redeemed at Gate'), ('CANCELLED', 'Voided / Cancelled')], default='VALID', max_length=20)),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='orders.orderitem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
